title: Mary Dahl's Website
page-top-title: Mary Dahl
top-section-bg-text: Mary Dahl | Aerospace Engineer
home-subtitle: Aerospace PhD Student at MIT
copyright-text: '&copy; Mary Dahl 2025. All Rights Reserved.'
